FONT_SIZE_SMALL = 10
FONT_SIZE_NORMAL = 12
FONT_SIZE_MEDIUM = 14
FONT_SIZE_LARGE = 17
FONT_SIZE_XLARGE = 22
FONT_SIZE_XXLARGE = 26
FONT_SIZE_TITLE = 36
FONT_SIZE_HUGE = 56
FONT_SIZE_ENORMOUS = 72

SPACING_XS = 1
SPACING_SMALL = 5
SPACING_NORMAL = 10
SPACING_MEDIUM = 12
SPACING_LARGE = 15
SPACING_XLARGE = 20
SPACING_XXLARGE = 25
SPACING_HUGE = 30
SPACING_ENORMOUS = 40
SPACING_MASSIVE = 50
SPACING_GIANT = 60
SPACING_TITLE = 75
SPACING_TITLE_LARGE = 110

WIDGET_HEIGHT_TAB = 20
WIDGET_HEIGHT_BUTTON = 20
WIDGET_HEIGHT_HEADER = 23
WIDGET_HEIGHT_SEPARATOR = 1
WIDGET_MIN_HEIGHT_PIE_CHART = 120

PADDING_XS = 2
PADDING_SMALL = 3
PADDING_MEDIUM = 5
PADDING_LARGE = 10

TABLE_ITEM_PADDING_VERTICAL = 3
TABLE_ITEM_PADDING_HORIZONTAL = 5
TABLE_COLUMN_EMPTY_WIDTH = 5
TABLE_ROW_HEIGHT = 20
TABLE_BORDER_WIDTH = 1
