from datetime import datetime
from typing import Protocol, runtime_checkable


@runtime_checkable
class LedgerService(Protocol):
    """Port UI → ledger (lecture + écritures append-only)."""

    async def list_accounts(self) -> list[str]: ...
    async def list_currencies(self) -> list[str]: ...
    async def list_currencies_for_account(self, account_id: str) -> list[str]: ...
    async def cash_balances(self, account_id: str) -> dict[str, float]: ...
    async def add_deposit(self, date: str, to_account: str, amount: float, currency: str,
                          replace_id: int | None = None) -> None: ...
    async def add_withdrawal(self, date: str, from_account: str, amount: float, currency: str,
                             replace_id: int | None = None) -> None: ...
    async def add_transfer(self, date: str, from_account: str, to_account: str, amount: float,
                           currency: str, replace_id: int | None = None) -> None: ...
    async def delete_entry(self, entry_id: int) -> None: ...
    async def list_entries(self, limit: int | None = None) -> list[dict]: ...
    async def list_instruments(self) -> list[dict]: ...
    async def instrument_context(self, conid: str) -> dict: ...
    async def next_lot_id(self, name: str, conid: str | None = None) -> str: ...
    async def add_trade(self, **trade) -> None: ...


@runtime_checkable
class PortfolioService(Protocol):
    """Port UI → moteur (lecture seule, USD)."""

    async def holdings_snapshot(self) -> list[dict]: ...
    async def cash(self) -> list[tuple[str, float, float]]: ...
    async def allocation(self) -> list[tuple[str, float, float]]: ...
    async def performance(self) -> list[dict]: ...
    async def daily_table(self, start: str, end: str) -> tuple[list[str], list[list]]: ...


@runtime_checkable
class MarketService(Protocol):
    """Port UI → IB Gateway (prix live, cash IB, détails de contrat)."""

    @property
    def connected(self) -> bool: ...
    async def refresh_live(self) -> datetime | None: ...
    async def last_update(self) -> datetime | None: ...
    async def ib_cash(self, account_id: str) -> dict[str, float]: ...
    async def contract_details(self, conid: str) -> dict | None: ...
    def close(self) -> None: ...
