# Dialog
DIALOG_WIDTH_TRADE_TICKET = 900
DIALOG_HEIGHT_TRADE_TICKET = 460
DIALOG_WIDTH_FUNDING = 470
DIALOG_HEIGHT_FUNDING = 318
BORDER_WIDTH = 2

# Section
SECTION_MARGIN_LEFT = 28
SECTION_SPACING = 3
INTERSECTION = 43

# Labels
LABEL_WIDTH_SMALL = 85
LABEL_WIDTH_MEDIUM = 170

# Inputs
INPUT_WIDTH_SMALL = 180
INPUT_WIDTH_LARGE = 210

# Spacers
SPACER_XS = 5
SPACER_SMALL = 10
SPACER_MEDIUM = 20
SPACER_LARGE = 40

# Values
VALUE_WIDTH_SMALL = 180
VALUE_WIDTH_LARGE = 210

# Buttons
BUTTON_WIDTH = 105
BUTTON_HEIGHT = 20
BUTTON_MARGIN_RIGHT = 15
BUTTON_MARGIN_BOTTOM = 15
BUTTON_SPACING = 13

# Spacing
SECTION_VERTICAL_SPACING = 15
